### ISSUE TITLE
Import and other accounts

### ISSUE THREAD

**Issue by geohacker** [mapbox/mapbox-data-team#13]
The team uses many special purpose accounts like http://www.openstreetmap.org/user/nammala_labuildings - for LA building imports. Let's track these also. 

Data https://github.com/mapbox/mapbox-data-team/blob/master/data/team.js
cc @batpad @maning

**Comment by geohacker** [comment]
@mapbox/team-data - can you all list your import and other OSM accounts we use to map for various projects? Thank you!

**Comment by kupendrayadav** [comment]
Upendra:

Regular OSM account username - [upendrakarukonda](https://www.openstreetmap.org/user/upendrakarukonda)
LA building OSM account username - [upendra_labuilding](http://www.openstreetmap.org/user/upendra_labuilding)

**Comment by abhisheksaikia** [comment]
Regular account: [saikabhi](https://www.openstreetmap.org/user/saikabhi)
LA building imports: [saikabhi_LA_imports](https://www.openstreetmap.org/user/saikabhi_LA_imports)
SF imports: [saikabhi_sfimport](https://www.openstreetmap.org/user/saikabhi_sfimport)

**Comment by Fa7C0n** [comment]
**OSM Regular**: [Fa7C0N](http://www.openstreetmap.org/user/Fa7C0N)
**OSM Imports**: [Fa7C0N_imports](http://www.openstreetmap.org/user/Fa7C0N_imports)

**Comment by bsrinivasa** [comment]
Here are the import accounts I have used so far.

- BharataHS_laimport
- BharataHS_import
- BharataHS_sfimport

**Comment by jinalfoflia** [comment]
#### OpenStreetMap accounts

Regular account: [jinalfoflia](https://www.openstreetmap.org/user/jinalfoflia)
LA building imports: [jinalfoflia_labuilding](https://www.openstreetmap.org/user/jinalfoflia_labuilding)

**Comment by chtnha** [comment]
**My OSM accounts**
OSM normal account: [Chetan_Gowda](https://www.openstreetmap.org/user/Chetan_Gowda)
LA building imports: chetan_labuildings
SF imports: chetan-sfimport

**Comment by Andygol** [comment]
Regular account: [andygol](https://osm.org/user/andygol)
I manage special account for import [addresses in Dnipro, Ukraine](https://github.com/osm-ua/dnipropetrovsk-addresses-import) - [dnipro_import](https://www.openstreetmap.org/user/dnipro_import)

**Comment by samely** [comment]
Regular account: [samely](https://www.openstreetmap.org/user/samely)
LA building import: [samely_labuildings](https://www.openstreetmap.org/user/samely_labuildings)

**Comment by dannykath** [comment]
Regular account: [dannykath](https://www.openstreetmap.org/user/dannykath)
LA building imports: [dannykath_labuildings](https://www.openstreetmap.org/user/dannykath_labuildings)

**Comment by geohacker** [comment]
thank you everyone. fixed in #14

**Comment by krishnanammala** [comment]
Regular account: nammala
LA building account: nammala_labuildings

**Comment by jothirnadh** [comment]
Regular account: [Jothirnadh](https://www.openstreetmap.org/user/Jothirnadh)
LA building account: [Jothirnadh_labuildings](https://www.openstreetmap.org/user/Jothirnadh_labuildings)
