### ISSUE TITLE
Adding new features to mapbox-data-team

### ISSUE THREAD

**Issue by kepta** [mapbox/mapbox-data-team#17]
Desirable features
- Ability to search based on a particular shape of data structure.
- Ability to get result based on a particular shape.

Sample Api

``` Javascript
var dTeam = require('mapbox-data-team');

dTeam.find(searchFilter, resultFilter);
```

Feature 1.
search by a particular a field

``` Javascript
// should return an array of all matches
dTeam.find({ 'fName': 'Abhishek' });
```

Feature 2
search by uid
``` Javascript
// should return an array of objects of all matches
dTeam.find({ 'uid': '2226712' });
```

Feature 3
shaping the result based on a shape object
``` Javascript
// should return all matches with field github and fname only
dTeam.find({ 'uid': '2226712' }, ['github', 'fname']);
```

Feature 4
shaping the result with other_accounts
``` Javascript
// should return all matches with field github and fname only
dTeam.find({}, ['github', 'other_accounts'] );
```

Feature 5
For queries which should only give singular result, we can have a similar API which returns the first match.

``` Javascript
// should return one match only with field github and fname
dTeam.findOne({ 'uid': '2226712' }, ['github', 'fname'] );
```
Feature 6

For complex queries find should also accept a filter function, which should filter the resulting data.
``` Javascript
// should return all matching with the function
dTeam.find( u => u.other_accounts.length > 0);

// should return first matching.
dTeam.findOne( u => u.other_accounts.length > 0);
```

Let me know if this would help in enriching this plugin.

cc @geohacker @batpad @ajithranka

**Comment by arunasank** [comment]
Thanks for fixing this is https://github.com/mapbox/mapbox-data-team/pull/18/. Closing!
