### ISSUE TITLE
Get confirmations that team details are correct

### ISSUE THREAD

**Issue by arunasank** [mapbox/mapbox-data-team#2]
👋 Please take some time to check if your details are correct in https://github.com/mapbox/mapbox-data-team/blob/master/data/team.js and comment below if things don't look okay. 

Check against your name once you've checked that your details are correct.

* [x] - @aaronlidman 
* [x] - @aarthykc 
* [x] - @abhisheksaikia 
* [x] - @ajithranka 
* [x] - @lxbarth 
* [x] - @Andygol 
* [x] - @planemad 
* [x] - @arunasank
* [x] - @bkowshik 
* [x] - @calfarome 
* [x] - @chtnha 
* [x] - @dannykath 
* [x] - @ediyes 
* [x] - @samely 
* [x] - @jinalfoflia 
* [x] - @jothirnadh 
* [x] - @karitotp 
* [x] - @luiswalter 
* [x] - @maanyaumashaanker 
* [x] - @maning 
* [x] - @manoharuss 
* [x] - @krishnanammala 
* [x] - @nikhilprabhakar 
* [x] - @oini 
* [x] - @ridixcr 
* [x] - @poornibadrinath 
* [x] - @pratikyadav 
* [x] - @ramyaragupathy 
* [x] - @RichRico 
* [x] - @Rub21 
* [x] - @ruthmaben 
* [x] - @geohacker 
* [x] - @batpad 
* [x] - @shvrm 
* [x] - @srividyacb 

Also, if your name isn't here and should be let me know!

**Comment by Andygol** [comment]
@arunasank 
Andrey Golovin - this is my name in Russian notation
Andrii Golovin - this is my name in Ukrainian international passport

In everyday life my friends and relatives call me Andrey. 

According to rule of transliteration from Ukrainian to latin script it will be
Андрій Головін -> Andrii Holovin

**Comment by chtnha** [comment]
@arunasank are you going to add OSM usernames that we use for `importing` purpose? Many of us have import accounts.

**Comment by arunasank** [comment]
@chtnha For now, let's keep these accounts out of the scope of the module and have it focus only on our day-to-day edits.

**Comment by ediyes** [comment]
Hi @arunasank my fullname is: Edith Yesenia Quispe Peréz

**Comment by arunasank** [comment]
@ediyes, @Andygol and everyone, I think I caused a bit of a confusion by asking you all to check your names. 😂 

I took the names off of the [team page](https://www.mapbox.com/about/team/). So if there's a difference between what's on there and what's in https://github.com/mapbox/mapbox-data-team/blob/master/data/team.js, do let me know!
