### ISSUE TITLE
Add new teammates from BLR

### ISSUE THREAD

**Issue by maning** [mapbox/mapbox-data-team#20]
@abhisheksaikia @ramyaragupathy

**Comment by ramyaragupathy** [comment]
waiting for @mugdha521 to add them to slack & github

**Comment by maning** [comment]
- [ ] 1. http://www.openstreetmap.org/user/Bhojaraj
- [ ] 2. http://www.openstreetmap.org/user/bhavana%20naga
- [ ] 3. http://www.openstreetmap.org/user/ashleyannmathew
- [ ] 4. http://www.openstreetmap.org/user/marthaleena
- [ ] 5. http://www.openstreetmap.org/user/muziriana

**Comment by geohacker** [comment]
@maning thank you! if you create a PR, I can take care of cutting new versions and deploying other stacks that use this information.

**Comment by abhisheksaikia** [comment]
@maning @geohacker PR created: https://github.com/mapbox/mapbox-data-team/pull/21

**Comment by kepta** [comment]
This was added in  #21
closing
